[package]
name = "cxlib_error"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
log.workspace = true
thiserror.workspace = true
ureq.workspace = true
onceinit.workspace = true