[package]
name = "cx_device_ident"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
cx_enc_utils = { path = "../cx_enc_utils", features = [
    "md5",
    "aes",
    "base64",
    "hex",
    "percent-encoding",
] }
getset2.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
