[package]
name = "cxlib"
edition = "2024"
version.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = ["crates/*", ".", "app/*", "gizmos/*"]

[workspace.package]
version = "0.4.0"
authors = ["worksoup"]

[workspace.dependencies]
bincode = "2.0"
chrono = "0.4"
derive-where = "1.5"
des = "0.8"
directories = "6.0"
flate2 = "1.1"
getset2 = "0.4"
hex = "0.4"
image = "0.25"
imageproc = "0.25"
inquire = "0.7"
log = { version = "0.4", features = ["release_max_level_info"] }
mime_guess = "2.0"
num_enum = "0.7"
num-traits = "0.2"
percent-encoding = "2.3"
rand = "0.9"
rayon = "1.10"
redb = "3.0"
rxing = "0.8"
serde = "1.0"
serde_json = "1.0"
sqlite = "0.37"
thiserror = "2.0"
toml = "0.9"
unicode-width = "0.2"
ureq = "3.0"
xcap = { version = "0.7" }
yapt = { git = "https://github.com/worksoup/yapt.git" }
############### cxlib_app ###############
clap = "4.5"
clap_complete_command = "0.6"
[features]
completion-all = ["completion-nu", "completion-carapace", "completion-fig"]
completion = ["cxlib_app/completion"]
completion-nu = ["cxlib_app/completion-nu"]
completion-carapace = ["cxlib_app/completion-carapace"]
completion-fig = ["cxlib_app/completion-fig"]

[dependencies]
cxlib_app = { path = "app/cxlib_app" }
cxlib_internal = { path = "crates/cxlib_internal" }
