[package]
name = "cxlib"
edition = "2021"
version.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = ["crates/*", ".", ]

[workspace.package]
version = "0.3.0"
authors = ["worksoup"]

[workspace.dependencies]
chrono = "0.4"
cookie_store = "0.21"
des = "0.8"
directories = "6.0"
flate2 = "1.0"
getset2 = "0.4"
hex = "0.4"
image = "0.25"
imageproc = "0.25"
inquire = "0.7"
log = { version = "0.4", features = ["release_max_level_info"] }
mime_guess = "2.0"
num_enum = "0.7"
num-traits = "0.2"
onceinit = "0.0.11"
percent-encoding = "2.3"
rand = "0.8"
rayon = "1.10"
rxing = "0.7"
serde = "1.0"
sqlite = "0.36"
thiserror = "2.0"
toml = "0.8"
unicode-width = "0.2"
ureq = "2.12"
xcap = { version = "0.2" }
yapt = { git = "https://github.com/worksoup/yapt.git" }

[dependencies]
cxlib_internal = { path = "crates/cxlib_internal" }
