[package]
name = "cxsign"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
edition = "2021"
package.version = "0.1.1"
package.authors = ["worksoup"]
members = ["crates/*"]
[workspace.dependencies]
ureq = "2.9"
cookie_store = "0.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dependencies]
#base = { path = "crates/base" }
#chrono = "0.4"
#clap = { version = "4.5", features = ["derive"] }
#cookie_store = "0.21"
#directories = "5.0"
#futures = "0.3"
#image = "0.24"
#inquire = "0.7"
#lazy_static = "1.4"
#percent-encoding = "2.3"
#rand = "0.8"
#reqwest = { version = "0.11", features = [
#    "json",
#    "cookies",
#    "gzip",
#    "deflate",
#    "cookie_store",
#    "multipart",
#] }
##reqwest_cookie_store = "0.6"
#rxing = "0.5"
#xcap = "0.0.4"
#serde = "1.0"
#serde_json = "1.0"
#serde_derive = "1.0"
#tokio = { version = "1.36", features = ["full"] }
#tokio-stream = "0.1"
#unicode-width = "0.1"
#num_enum = "0.7"

# url = "2.4"
# strfmt = "*"
# utf8_slice = "1.0"
# trauma = "2.2"
# thread_local = "1.1"
# ctrlc = "3.4"
# regex = "1.10"
# toml = "0.8"
