[package]
name = "cxlib_default_impl"
edition = "2024"
version.workspace = true
authors.workspace = true
[features]
default = ["upload-file"]
upload-file = ["cxlib_types/upload-file"]
[dependencies]
cx_interact = { path = "../../gizmos/cx_interact" }
cxlib_captcha = { path = "../cxlib_captcha" }
cxlib_error_utils = { path = "../cxlib_error_utils" }
cxlib_imageproc = { path = "../cxlib_imageproc" }
cxlib_protocol = { path = "../cxlib_protocol", features = [] }
cxlib_sign = { path = "../cxlib_sign" }
cxlib_types = { path = "../cxlib_types" }
derive-where.workspace = true
image.workspace = true
log.workspace = true
ref_wrapper = { path = "../../gizmos/ref_wrapper" }
rxing.workspace = true
serde = { workspace = true, features = ["derive"] }
try_from_with_context = { path = "../../gizmos/try_from_with_context" }
yapt.workspace = true
[target.'cfg(any(target_os = "linux", target_os = "windows", target_os = "macos"))'.dependencies]
xcap.workspace = true
