[package]
name = "cxlib_utils"
edition = "2021"
version.workspace = true
authors.workspace = true

[features]

[dependencies]
inquire.workspace = true
log.workspace = true
unicode-width.workspace = true
rxing.workspace = true
ureq.workspace = true
