[package]
name = "cxlib_app"
edition = "2021"
version.workspace = true
authors.workspace = true

[features]
completion = ["dep:clap_complete_command"]
completion-nu = ["completion", "clap_complete_command/nushell"]
completion-carapace = ["completion", "clap_complete_command/carapace"]
completion-fig = ["completion", "clap_complete_command/fig"]

[dependencies]
clap = { workspace = true, features = ["derive", "cargo"] }
clap_complete_command = { workspace = true, optional = true }
inquire.workspace = true
log.workspace = true
chrono.workspace = true
cxlib_internal = { path = "../cxlib_internal" }