[package]
name = "cxsign_utils"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
inquire = "0.7"
flate2 = "*"
log.workspace = true
unicode-width = "0.1"