[package]
name = "cxlib_captcha"
edition = "2024"
version.workspace = true
authors.workspace = true

[features]

[dependencies]
yapt.workspace = true
cxlib_base_types = { path = "../cxlib_base_types" }
cxlib_error = { path = "../cxlib_error" }
cxlib_error_utils = { path = "../cxlib_error_utils" }
cx_debug_utils = { path = "../../gizmos/cx_debug_utils" }
cx_ureq_utils = { path = "../../gizmos/cx_ureq_utils" }
cxlib_imageproc = { path = "../cxlib_imageproc" }
cxlib_obfuscate = { path = "../cxlib_obfuscate" }
cxlib_protocol = { path = "../cxlib_protocol", features = ["captcha"] }
getset2.workspace = true
hex.workspace = true
image.workspace = true
log.workspace = true
rand.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
ureq = { workspace = true, features = ["cookies", "json"] }
