[package]
name = "cxlib_base_types"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
bincode.workspace = true
getset2 = { workspace = true }
ref_wrapper = { path = "../../gizmos/ref_wrapper" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
