[package]
name = "cxlib_types_ext"
edition = "2024"
version.workspace = true
authors.workspace = true

[dependencies]
cxlib_error_utils = { path = "../cxlib_error_utils" }
cxlib_types = { path = "../cxlib_types" }
cxlib_protocol = { path = "../cxlib_protocol" }
thiserror.workspace = true
log.workspace = true
