[package]
name = "cxlib_imageproc"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
image.workspace = true
imageproc.workspace = true
num-traits.workspace = true
ureq = { workspace = true, features = ["cookies", "json"] }