[package]
name = "cxlib_imageproc"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
image.workspace = true
num-traits.workspace = true
imageproc.workspace = true
rayon.workspace = true
yapt = { workspace = true, features = ["imageproc"] }
