[package]
name = "cxsign_obfuscate"
edition = "2021"
version.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
#syn = "*"
quote = "*"
proc-macro2 = "*"
cxsign_utils = { path = "../cxsign_utils" }