[package]
name = "cxlib_pan"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
cxlib_protocol = { path = "../cxlib_protocol" }
mime_guess.workspace = true
log.workspace = true
rand.workspace = true
ureq = { workspace = true, features = ["cookies", "json"] }