[package]
name = "cxlib_protocol"
edition = "2024"
version.workspace = true
authors.workspace = true
[features]
default = []
captcha = ["ureq", "percent-encoding"]
default_impl = ["ureq"]
sign = ["ureq"]
netdisk = ["ureq"]
types = ["ureq"]
unused = ["ureq"]
user = ["ureq", "rand"]
multipart = ["rand"]
upload-file = ["multipart", "mime_guess"]
[dependencies]
cx_gizmo_types = { path = "../../gizmos/cx_gizmo_types" }
cxlib_base_types = { path = "../cxlib_base_types" }
cxlib_error = { path = "../cxlib_error" }
cxlib_error_utils = { path = "../cxlib_error_utils" }
getset2 = { workspace = true }
log.workspace = true
mime_guess = { workspace = true, optional = true }
percent-encoding = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror.workspace = true
ureq = { workspace = true, optional = true }
