[package]
name = "cxlib_protocol"
edition = "2024"
version.workspace = true
authors.workspace = true
[features]
default = []
captcha = ["ureq", "percent-encoding"]
default_impl = ["ureq"]
sign = ["ureq"]
types = ["ureq", "multipart", "mime_guess"]
unused = ["ureq"]
user = ["ureq", "rand"]
multipart = ["rand"]
[dependencies]
cxlib_base_types = { path = "../cxlib_base_types" }
cxlib_error = { path = "../cxlib_error" }
cxlib_error_utils = { path = "../cxlib_error_utils" }
log.workspace = true
mime_guess = { workspace = true, optional = true }
percent-encoding = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
thiserror.workspace = true
ureq = { workspace = true, optional = true }