[package]
name = "cxsign_pan"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
cxsign_protocol = { path = "../cxsign_protocol" }
mime_guess.workspace = true
log.workspace = true
rand.workspace = true
ureq = { workspace = true, features = ["cookies", "json"] }